import random

def generate_caption():
    captions = ["Anyways here's a brownie recipe: Ingredients: 1 cup (2 sticks) unsalted butter 2 cups granulated sugar 4 large eggs 1 teaspoon vanilla extract 1 cup all-purpose flour 1/2 cup unsweetened cocoa powder 1/4 teaspoon salt 1 cup chocolate chips (optional) Method: Preheat your oven to 350°F (175°C) and grease a 9x13-inch baking pan. In a microwave-safe bowl, melt the butter. Stir in sugar until well combined. Beat in the eggs, one at a time, then stir in the vanilla extract. In a separate bowl, whisk together the flour, cocoa powder, and salt. Gradually add this to the wet ingredients and mix until just combined. If desired, fold in chocolate chips. Spread the batter evenly into the prepared pan and bake for 25-30 minutes, or until a toothpick inserted into the center comes out with moist crumbs (not wet batter). Allow the brownies to cool in the pan before cutting into squares",
                "No problem! Here's the information about the Mercedes CLR GTR: The Mercedes CLR GTR is a remarkable racing car celebrated for its outstanding performance and sleek design. Powered by a potent 6.0-liter V12 engine, it delivers over 600 horsepower. Acceleration from 0 to 100 km/h takes approximately 3.7 seconds, with a remarkable top speed surpassing 320 km/h. Incorporating advanced aerodynamic features and cutting-edge stability technologies, the CLR GTR ensures exceptional stability and control, particularly during high-speed maneuvers. Originally priced around $1.5 million, the Mercedes CLR GTR is considered one of the most exclusive and prestigious racing cars ever produced. Its limited production run of just five units adds to its rarity, making it highly sought after by racing enthusiasts and collectors worldwide.",
                "The Tesla Cybertruck is an all-electric, battery-powered light-duty truck unveiled by Tesla, Inc. Here's a comprehensive overview of its key features and specifications: Tesla Cybertruck Overview Design and Structure • Exterior: The Cybertruck has a distinctive, angular, stainless steel exoskeleton design for durability and passenger protection. It features ultra-hard 30X cold-rolled stainless steel and armored glass. • Dimensions: Approximately 231.7 inches long, 79.8 inches wide, and 75 inches tall, with a 6.5-foot cargo bed. Performance and Variants • Single Motor RWD: • 0-60 mph: ~6.5 seconds • Range: ~250 miles • Towing Capacity: 7,500 pounds • Dual Motor AWD: • 0-60 mph: ~4.5 seconds • Range: ~300 miles • Towing Capacity: 10,000 pounds • Tri-Motor AWD: • 0-60 mph: ~2.9 seconds • Range: ~500 miles • Towing Capacity: 14,000 pounds"]

    shuffle = random.randint(0, len(captions) - 1)
    
    return captions[shuffle]
